services:
  mysql:
    image: mysql:8.0 # 생성이미지:버전
    container_name: questday_mysql
    restart: always # 수동종료 전까지 항상 켜지도록 유지 (sleep 방지)
    ports:
      - "13306:3306" # 포트번호 host:docker 로컬 포트에 도커 포트를 마운트
    volumes:
      - ./db/mysql/data:/var/lib/mysql # 로컬저장경로:도커저장경로 (컨테이너 종료 후에도 데이터를 로컬에 저장하여 유지)
      - ./db/mysql/init:/docker-entrypoint-initdb.d # 로컬저장경로:도커저장경로 / 해당 경로에 작성된 DDL을 컨테이너 생성 시 자동 실행
    environment:
      #=== 환경 변수 ===#
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSWORD} # root 계정 비밀번호 설정
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE} # 데이터베이스 생성 이름
      MYSQL_CHARSET: ${DOCKER_MYSQL_CHARSET} # 인코딩 문자
      MYSQL_COLLATION: ${DOCKER_MYSQL_COLLATION} # 대조 문자
      TZ: ${DOCKER_TZ} # 타임존 설정

  redis:
    image: redis:7.0
    container_name: questday_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./db/redis/data:/data
    command: [ "redis-server", "--requirepass", "${DOCKER_REDIS_PASSWORD}" ]
    environment:
      TZ: ${DOCKER_TZ}
